@startuml DER-2canciones

entity Playlist {
  id : int <<PK>>
  --
  visibilidad_id : int <<FK>>
  contenido_id : int <<FK>>
}

entity Contenido {
  id : int <<PK>>
  --
  likes : int
  dislikes : int
  fechaInicio : Date
  fechaFin : Date
  fechaSubida : Date
  duracion : Time
  ' embebo estadistica
  ' Dejo todas aca, porque uso SintleTable
}

entity Usuario_x_Playlist {
  usuario_id : int <<PK/FK>>
  playlist_id : int <<PK/FK>>
  --
}

entity Contenido_x_Playlist {
  contenido_id : int <<PK/FK>>
  playlist_id : int <<PK/FK>>
  --
  orden : int
}

entity Usuario {
  id : int <<PK>>
  --
  playlist_id : int <<FK>>
  nombre : String
}


Playlist --{ Usuario_x_Playlist
Usuario -right-{ Usuario_x_Playlist
Playlist ||-left|{ Contenido_x_Playlist
Contenido ||-|{ Contenido_x_Playlist
Playlist }--|| Usuario
Contenido -right-|| Usuario

@enduml